ALTER TABLE `user_modifier` ADD COLUMN `action_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `airline_modifier` ADD COLUMN `action_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
